name: Terraform Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  id-token: write   # required for AWS OIDC

env:
  TF_VAR_CLOUDFLARE_GLOBAL_API_TOKEN: ${{ secrets.CLOUDFLARE_GLOBAL_API_TOKEN }}
  TF_VAR_CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug network
        run: |
          nslookup api.cloudflare.com
          curl -I https://api.cloudflare.com/client/v4/user/tokens/verify

      - name: Debug env
        run: |
          env | grep TF_VAR

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Cloud auth
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }
          EOF

      # -----------------------------
      # AWS AUTH (OIDC â€” required)
      # -----------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495599767146:role/github-terraform
          aws-region: us-west-1

      # -----------------------------
      # Terraform lifecycle
      # -----------------------------
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H 204.236.176.6 >> ~/.ssh/known_hosts

      - name: Run Ansible to deploy certs and configure nginx
        run: |
          ansible-playbook -i inventory.ini site.yml \
            --extra-vars "tls_cert_path=origin.crt tls_key_path=origin.key"
